apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: devsecops-aws-secrets
  namespace: default
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "devsecops/app-secrets"
        objectType: "secretsmanager"
        jmesPath:
          - path: "APP_SECRET_KEY"
            objectAlias: "APP_SECRET_KEY"
          - path: "DB_PASSWORD"
            objectAlias: "DB_PASSWORD"
  secretObjects:
    - secretName: devsecops-app-secrets
      type: Opaque
      data:
        - objectName: APP_SECRET_KEY
          key: APP_SECRET_KEY
        - objectName: DB_PASSWORD
          key: DB_PASSWORD